# Generated by Django 2.0.7 on 2018-08-13 04:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='profileimg',
            field=models.ImageField(upload_to='static/'),
        ),
    ]
