# Generated by Django 2.0.7 on 2018-08-16 08:50

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(blank=True, max_length=100)),
                ('Body', models.TextField(blank=True)),
                ('Posted_on', models.DateField(default=datetime.datetime.today)),
            ],
        ),
    ]
