# Generated by Django 2.0.7 on 2018-08-17 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20180817_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.AddField(
            model_name='post',
            name='username',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
