# Generated by Django 2.0.7 on 2018-08-17 07:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20180817_1259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.OneToOneField(default='master', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
