# Generated by Django 2.0.7 on 2018-08-18 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20180818_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='Title',
        ),
    ]
