# Generated by Django 2.0.7 on 2018-08-30 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20180830_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='profileimg',
            field=models.ImageField(default='', upload_to='static'),
        ),
    ]
