# Generated by Django 2.0.7 on 2018-09-01 05:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_comment_profileimg'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='postid',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Post'),
        ),
    ]
