# Generated by Django 2.0.7 on 2018-09-01 05:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_auto_20180901_1105'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='postid',
        ),
        migrations.AlterField(
            model_name='post',
            name='id',
            field=models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
