# Generated by Django 2.0.7 on 2018-09-01 06:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0017_auto_20180901_1124'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='Title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Post'),
        ),
    ]
