# Generated by Django 2.0.7 on 2018-09-01 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0018_auto_20180901_1144'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='Title',
        ),
    ]
