# Generated by Django 2.0.7 on 2018-09-01 06:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_remove_comment_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, to='accounts.Post'),
        ),
    ]
